version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FitnessStaticWebsite-Gamma"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gu289f3keoz9"
s3_prefix = "web-app-gamma"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

